title: Anonymous Function
description: 'A meetup for future tech leaders'

url: "http://anonymousfunction.org"
timezone: Europe/Berlin

destination: _site
permalink: /:year/:month/:title/
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

include: ['_pages']
exclude: ['Gemfile', 'Gemfile.lock']

enable_retina: false
nav_list:
  Home: ['Home', '/', 'fa-home']
  About: ['About', '/about', 'fa-anchor']
  Team: ['Team', '/team', 'fa-users']
#  Contact: ['Contact', '/contact', 'fa-plane']
  Code Of Conduct: ['Code Of Conduct', '/code-of-conduct', 'fa-handshake-o']

single_footer: '<p>Anonymous Function: A meetup for future tech leaders. Paul Adams &copy; 2017</p>'

footer_links:
    About: ['About', '/about']
    Writer: ['Paul Adams &copy; 2017', '/about']

permalink: /posts/:year/:month/:title

collections:
  team:
    output: true
    permalink: /team/:title

defaults:
  - scope:
      path: ""
      type: "team"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post-sidebar"