title: Anonymous Function
description: A meetup for future tech leaders

theme: jekyll-theme-minimal

destination: _site
paginate: 5
permalink: /:year/:month/:title/
markdown: kramdown
timezone: Europe/Berlin

kramdown:
  input: GFM
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['Gemfile', 'Gemfile.lock']

collections:
  news:
    output: true
    permalink: /news/:year/:month/:title/