title: Anonymous Function
description: A meetup for future tech leaders

theme: jekyll-theme-minimal

destination: _site
paginate: 5
permalink: /:year/:month/:title/
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['Gemfile', 'Gemfile.lock']
include: ['_news']
